input-field {
    size              = 250, 40
    position          = 100, 250
    valign            = bottom
    halign            = left


    rounding          = 5
    outline_thickness = 2

    outer_color       = $accent_primary
    inner_color       = $surface
    font_color        = $text_primary
    check_color       = $success
    fail_color        = $error
    capslock_color    = $warning

    dots_size         = 0.3
    dots_text_format  = 

    fade_on_empty     = false

    font_family       = $font
    placeholder_text  = 󰌾 <b>Do you remember?</b>
    fail_text         = 󱃞 <b>Are you really $USER?</b>
}

# --- USERNAME FIELD --- #
shape {
    size         = 250, 40
    position     = 100, 320
    valign       = bottom
    halign       = left
    rounding     = 5
    border_size  = 2

    color        = $surface
    border_color = $accent_primary
    zindex       = -8
}

# --- USERNAME LABEL --- #
label {
    position    = 185, 330
    valign      = bottom
    halign      = left

    text        =  <i><b>$USER</b></i>
    font_size   = 13
    font_family = $font

    color       = $text_primary
    font_family = $font
}

# --- USER iMAGE --- #
image {
    position    = 170, 400
    valign      = bottom
    halign      = left
    path        = ~/.config/hypr/images/pfp.jpg
    size        = 120
}

