background {
    monitor     =
    path        = $bg_img
    blur_passes = 0
    blur_size   = 5
    zindex      = -10
}

# --- AUTH GLASS LAYER -- #
shape {
    size   = 35%, 100%
    halign = left
    color  = $background_50
    zindex = -9
}
