# --- TIME --- #
label {
    position    = 120, -80
    valign      = top
    halign      = left
    
    text        = $TIME12
    font_size   = 35
    font_family = $font
}

# --- DATE --- #
label {
    position    = 150, -150
    valign      = top
    halign      = left
    
    text        = cmd[update:1000] echo "<span>$(date +"%d") $(date +"%h") $(date +"%y") | $(date +"%a")</span>"
    font_size   = 15 
    font_family = $font
}

