shape {
    size         = 35, 35
    position     = -20, -20
    halign       = right
    valign       = top
    color        = $surface
    border_size  = 2
    rounding     = 5
    border_color = $accent_primary
}

label {
    position    = -32, -29
    halign      = right
    valign      = top
    text        = 
    font_size   = 12
    font_family = $font
    color       = $accent_primary
}
