# --- POWER BUTTON --- #
shape {
    size         = 35, 35
    position     = 100, 150
    valign       = bottom
    halign       = left

    rounding     = 5
    border_size  = 2

    color        = $surface
    border_color = $accent_primary

    onclick      = systemctl poweroff
    zindex       = -8
}

label {
    position    = 113, 158
    valign      = bottom
    halign      = left

    text        = 
    font_size   = 12
    font_family = $font
    color       = $text_primary
}

# --- RESTART BUTTON --- #
shape {
    size         = 35, 35
    position     = 207, 150
    valign       = bottom
    halign       = left

    rounding     = 5
    border_size  = 2

    color        = $surface
    border_color = $accent_primary

    onclick      = systemctl reboot
    zindex       = -8
}

label {
    position    = 220, 159
    valign      = bottom
    halign      = left

    text        = 
    font_size   = 12
    font_family = $font
    color       = $text_primary
}

# --- SLEEP BUTTON --- # 
shape {
    size         = 35, 35
    position     = 310, 150
    valign       = bottom
    halign       = left

    rounding     = 5
    border_size  = 2

    color        = $surface
    border_color = $accent_primary

    onclick      = systemctl suspend
    zindex       = -8
}

label {
    position    = 323, 158
    valign      = bottom
    halign      = left

    text        = 󰤄
    font_size   = 13
    font_family = $font
    color       = $text_primary
}

