
animations {
    enabled = true
    workspace_wraparound = true
    
    # --- BEZIER DECLARATIONS --- #
    bezier = easeOutQuint,   0.23, 1,     0.32,  1
    bezier = easeInOutCubic, 0.65, 0.05,  0.36,  1
    bezier = linear,         0,    0,     1,     1
    bezier = almostLinear,   0.5,  0.5,   0.75,  1
    bezier = quick,          0.15, 0,     0.1,   1
    bezier = easeInOutBack,  0.68, -0.55, 0.265, 1.55
    bezier = easeInGrowPop, 0.31, 0.42, 0.5,1.45

    # --- WORKSPACE ANIMATIONS --- #
    animation = workspaces,           1,     1.94,  easeInOutBack,  slide
    animation = workspacesIn,         1,     4,     easeInOutBack,  slide right
    animation = workspacesOut,        1,     1.94,  easeInOutCubic, slide left
    animation = specialWorkspaceIn,   1,     4,     easeInOutBack,  slidevert 
    animation = specialWorkspaceOut,  1,     4,     easeInOutBack, slidevert

    # --- WINDOW ANIMATIONS --- #
    animation = windows,       1, 4.8,  easeInOutBack
    animation = windowsIn,     1, 4.1,  easeInGrowPop, popin 20%
    animation = windowsOut,    1, 4.0,  easeInGrowPop, popin 20%
    animation = fade,          1, 3.0,  almostLinear

    # --- LAYER ANIMATIONS --- #
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint,   popin 20%
    animation = layersOut,     1,     4,     easeOutQuint,   popin 20%

    # --- Others --- #
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = zoomFactor,    1,     7,     quick
}
