exec-once = hyprctl setcursor macOS 24
exec-once = swww img "$wallpaper" --transition-type center
exec-once = waybar
exec-once = swaync
exec-once = swayosd-server
exec-once = hypridle
exec-once = ~/.config/shared/scripts/play-startup-sound.sh
