exec-once = hyprctl setcursor macOS 32
exec-once = waypaper --restore
exec-once = waybar 
exec-once = swaync 
exec-once = swayosd-server
exec-once = hypridle 
exec-once = ~/.config/shared/scripts/play-startup-sound.sh
