
# --- DEFAULT APPLICATIONS ---
$terminal    = kitty
$fileManager = dolphin
$launcher    = rofi -show drun -theme ~/.config/rofi/themes/launcher.rasi
$browser     = zen-browser

# --- KEYBINDINGS --- 
$mainMod = SUPER

# --- SCRIPTS ---
$openPowerMenu = $HOME/.config/shared/scripts/power-menu.sh 
