
# --- BASE WINDOW RULES ---
windowrule = suppressevent maximize, class:.* # Ignore maximize requests from apps. You'll probably like this.
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrule = float, center, class:xdg-desktop-portal-gtk
windowrule = animation slide, class:xdg-desktop-portal-gtk
windowrule = size 800 500, class:xdg-desktop-portal-gtk

windowrule = float, center, class:org.gnome.gThumb
windowrule = animation slide, class:org.gnome.gThumb
windowrule = size 800 500, class:org.gnome.gThumb

layerrule = animation slide, waybar
layerrule = animation slide right, swaync-control-center
layerrule = animation slide right, swaync-notification-window

layerrule = blur, rofi
layerrule = xray on, rofi
layerrule = animation slide bottom, rofi

layerrule = animation popin 60%, swayosd
