
# --- BASE WINDOW RULES ---
windowrule = suppressevent maximize, class:.* # Ignore maximize requests from apps. You'll probably like this.
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0


layerrule = animation slide, waybar
layerrule = animation slide right, swaync-control-center
layerrule = animation slide right, swaync-notification-window

layerrule = blur, rofi
layerrule = xray on, rofi
layerrule = animation slide bottom, rofi

layerrule = animation popin 60%, swayosd
