foreground              #d6d8ee
background              #1a1b26
cursor                  #b38eed
selection_foreground    #1a1b26
selection_background    #9aa5ce

color0                  #1c0f30
color1                  #6357E8
color2                  #7052F8
color3                  #983CCF
color4                  #995AED
color5                  #D96EF4
color6                  #5fd7d3
color7                  #edc6f2

color8                  #a58aa9
color9                  #6357E8
color10                 #7052F8
color11                 #983CCF
color12                 #995AED
color13                 #D96EF4
color14                 #7182FE
color15                 #edc6f2

active_border_color     #b38eed
inactive_border_color   #222436
bell_border_color       #f0b775

url_color               #b38eed

active_tab_foreground   #1a1b26
active_tab_background   #b38eed
inactive_tab_foreground #222436
inactive_tab_background #edc6f2

mark1_foreground        #1a1b26
mark1_background        #50fa7b
mark2_foreground        #1a1b26
mark2_background        #f0b775
mark3_foreground        #1a1b26
mark3_background        #f7768e
