*{
   background       :   #1a1b26;
   surface          :   #222436;
   text-primary     :   #d6d8ee;
   text-secondary   :   #a3accf;
   accent-primary   :   #b38eed;
   accent-secondary :   #5fd7d3;
   highlight        :   #9aa5ce;
   success          :   #50fa7b;
   warning          :   #f0b775;
   error            :   #f7768e;
}
