$background       = rgb(1a1b26)
$background_50 = rgba(1a1b2699)
$surface          = rgb(222436)
$text_primary     = rgb(d6d8ee)
$text_secondary   = rgb(a3accf)
$accent_primary   = rgb(b38eed)
$accent_secondary = rgb(edc6f2)
$highlight        = rgb(9aa5ce)
$success          = rgb(50fa7b)
$warning          = rgb(f0b775)
$error            = rgb(f7768e)
