source = ~/.config/shared/styles/hypr-colors.conf
source = ~/.config/hypr/modules/hyprlock/variables.conf

source = ~/.config/hypr/modules/hyprlock/background.conf
source = ~/.config/hypr/modules/hyprlock/general-configs.conf
source = ~/.config/hypr/modules/hyprlock/date-time.conf
source = ~/.config/hypr/modules/hyprlock/auth.conf
source = ~/.config/hypr/modules/hyprlock/power-options.conf
source = ~/.config/hypr/modules/hyprlock/logo.conf
