source = ~/.config/themes/build/hypr/colors.conf
source = ./modules/variables.conf
source = ./modules/environment.conf
source = ./modules/monitors.conf
source = ./modules/appearance.conf
source = ./modules/animations.conf
source = ./modules/window-rules.conf
source = ./modules/keybindings.conf
source = ./modules/permissions.conf
source = ./modules/autostart.conf
