include                     ~/.config/themes/current-theme/colors/kitty-colors.conf

font_family                 JetBrains Mono Nerd Font
font_size                   13.0

window_padding_width        15
scrollback_lines          5000
scrollbar_radius            1

cursor_trail                4
background_opacity          0.5
paste_actions               quote-urls-at-prompt,confirm
shell_integration           enabled
strip_trailing_spaces       smart
notify_on_cmd_finish        unfocused
allow_remote_control        yes

tab_bar_edge                top
tab_bar_style               powerline
tab_bar_min_tabs            1

map ctrl+t                  new_tab
map ctrl+w                  close_tab
map ctrl+shift+r            set_tab_title
map ctrl+]                  next_tab
map ctrl+[                  previous_tab
map ctrl+shift+h            move_tab_forward
map ctrl+shift+l            move_tab_backward
