*{
 background       :  #2C2C2C;
 surface          :  #545454;
 foreground       :  #E9E9E9;

 accent           :  #E0E0E0;
 accent-hover     :  #D1D1D1;
 accent-foreground:  #202020;

 success          :  #4FD08A;
 warning          :  #E6A84A;
 error            :  #E05D6F;
}
