$background        = rgb(2C2C2C)
$background_50     = rgba(2C2C2C99)
$surface           = rgb(545454)
$foreground        = rgb(E9E9E9)

$accent            = rgb(E0E0E0)
$accent_hover      = rgb(D1D1D1)

$success           = rgb(4FD08A)
$warning           = rgb(E6A84A)
$error             = rgb(E05D6F)
